---

- name: Setup web server
  hosts: linux
  become: true
  become_method : sudo

  tasks:
   - name: Install Apache
     apt:
        name: apache2
        # Checks if apache is present and if not,installs apache
        state: present

  - name: set timezone to Africa/Lagos
     tags: time
     timezone: name=Africa/Lagos

  - name: print hostname on server
     tags: printf
     shell: echo "<h1>This is my host name $(hostname -f) by Amadi Daniel</h1>" > /var/www/html/index.html

  - name: restart apache2
     tags: restart
     service:
       name: apache2
       state: restarted